development:
  adapter: postgresql
  database: team8project_dev
  host: localhost
  min_messages: warning
  username:

test:
  adapter: postgresql
  database: team8project_test
  host: localhost
  min_messages: warning
  username: